;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Wed Oct 29 2025
; Processor: 8086
; Compiler:  MASM32
;
; Before starting simulation set Internal Memory Size 
; in the 8086 model properties to 0x10000
;====================================================================

DATA SEGMENT
      
      PORTA EQU 80H; 7-SEGMENTS
      PORTB EQU 82H; BUTTONS
      PORTC EQU 84H; SWITCHES (for binary nums)
      COM_REG EQU 86H
      
      ORG 00000H
DATA ENDS

CODE    SEGMENT PUBLIC 'CODE'
        ASSUME CS:CODE
	
	MOV AX, DATA ; Move stuff from Data Segment in AX (for us to use em)
	MOV DS, AX
	ORG 0000H; Starting point for memory
	
	;Clears out registers and set to 0
	XOR AX,AX
	XOR BX,BX
	XOR CX,CX
	XOR DX,DX
	
;PUBLIC STATIC VOID MAIN (ARGS)
;=================================
START:
	 ;Standard stup for 8255
	 MOV DX, COM_REG
	 MOV AL, 10001011B ; Standard binary value for setup
	 OUT DX, AL
	
         ;Wait for user input (asynchronous wait)	
	 WAIT_INPUT:
	 
	 ;This like saying (whatever I out in PortB (swithes), goes to AL)
	 ;EX. 0001B -> AL = 0001b
	 
	 ;Port B goes to DX
	 MOV DX, PORTB
	 ;DX goes to AL
	 IN AL, DX
	 
	 CMP AL, 0001B
	 JE _ADDITION
	 
	 CMP AL, 0010B
	 JE _SUBTRACTION
	 
	 CMP AL, 0100B
	 JE _MULTIPLICATION
	 
	 CMP AL, 1000B
	 JE _DIVISION
	
	 JMP WAIT_INPUT
	 
;Commands for operation	


_ADDITION:
	 ;ALWAYS PUT THIS BEFOTE YOUR STUFF
	 MOV DX, PORTC
	 IN AL, DX
	 
	 MOV AH, AL
	 MOV CL, 04H
	 SHR AL, CL
	 AND AH, 0FH
	 
	 ;Addition function
	 ADD AL, AH
	 MOV CH, 10
	 MOV BL, AL
	 
	 ;Wipe clean
	 XOR AX, AX
	 MOV AL, BL
	 DIV CH
	 
	 SHL AL, CL
	 OR AL, AH
	 MOV BL, AL
	 ;Wipe clean again
	 XOR AX, AX
	 
	 ;Shows yer stuff
	 MOV AL, BL ;Move result (BL) to AL 
	 MOV DX, PORTA ;Load port A (output)
	 OUT DX, AL ;AL goes out to Port A
	 JMP WAIT_INPUT ;Go back to waiting input
	  
_SUBTRACTION:
	 ;ALWAYS PUT THIS BEFOTE YOUR STUFF
	 MOV DX, PORTC
	 IN AL, DX
	 
	 MOV AH, AL
	 MOV CL, 04H
	 SHR AL, CL
	 AND AH, 0FH
	 
	 SUB AH, AL
	 JS _NEGATIVE
	 
	 MOV BL, AH
	 XOR AX, AX
	 MOV AL, BL
	 MOV CH, 10
	 DIV CH
	 SHL AL, CL
	 ADD AL, AH
	 MOV BL, AL
	 
	 MOV DX, PORTA
	 OUT DX, AL
	 JMP WAIT_INPUT
	 
	 _NEGATIVE: 
	  MOV DX, PORTA
	  MOV AL, 0AAH
	  OUT DX, AL
	  JMP WAIT_INPUT
	 
	 SHL AL, CL
	 OR AL, AH
	 MOV BL, AL
	 XOR AX, AX
	 
	 ;Shows yer stuff
	 MOV AL, BL ;Move result (BL) to AL 
	 MOV DX, PORTA ;Load port A (output)
	 OUT DX, AL ;AL goes out to Port A
	 JMP WAIT_INPUT ;Go back to waiting input
	 
_MULTIPLICATION:
	 ;ALWAYS PUT THIS BEFOTE YOUR STUFF
	 MOV DX, PORTC
	 IN AL, DX
	 
	 MOV AH, AL
	 MOV CL, 04H
	 SHR AL, CL
	 AND AH, 0FH
	 MOV BL, AH
	 MUL BL
	 
	 CMP AL, 63H
	 JA _OVER
	 
	 MOV CH, 10
	 MOV BL, AL
	 XOR AX, AX
	 MOV AL, BL
	 DIV CH
	 SHL AL, CL
	 ADD AL, AH
	 MOV BL, AL
	 XOR AX, AX
	 
	 ;Shows yer stuff
	 MOV AL, BL ;Move result (BL) to AL 
	 MOV DX, PORTA ;Load port A (output)
	 OUT DX, AL ;AL goes out to Port A
	 JMP WAIT_INPUT ;Go back to waiting input
	 
	 _OVER:
	 MOV AL, 0BBH
	 MOV DX, PORTA
	 OUT DX, AL
	 JMP WAIT_INPUT
	 
_DIVISION:
	 ;ALWAYS PUT THIS BEFOTE YOUR STUFF
	 MOV DX, PORTC
	 IN AL, DX
	 
	 MOV AH, AL
	 ;Shif value of 4
	 MOV CL, 04H
	 
	 ;Shift AH by CL (4): why the fuck does this happen???
	 SHR AH, CL
	 
	 ;Preparing to divide it
	 AND AL, 0FH
	 MOV BL, AH
	 MOV AH, 0
	 ;Divide AL with BL (why AL? Its standard)
	 DIV BL
	 ;Move result to BL
	 MOV BL, AL
	 ;Wiping it clean
	 XOR AX, AX
	 
	 ;Shows yer stuff
	 MOV AL, BL ;Move result (BL) to AL 
	 MOV DX, PORTA ;Load port A (output)
	 OUT DX, AL ;AL goes out to Port A
	 JMP WAIT_INPUT ;Go back to waiting input
	

ENDLESS:
        JMP ENDLESS
CODE    ENDS
        END START