# -*- coding: utf-8 -*-
"""NumberClassification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11HCzf77sI7v6-fDKWAuwPkIUVdLmiSBq
"""
import numpy as np
from matplotlib import pyplot as plt
import os
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout, BatchNormalization
from tensorflow.keras.preprocessing.image import ImageDataGenerator

#IMPORTANT: RUN MODEL ON CPU, since the dataset is small and it will run faster on CPU than GPU.
os.environ['CUDA_VISIBLE_DEVICES'] = '-1'


# STEP 1: Load the data into 'coarse labels'
(coarse_train, coarse_Trlabels), (coarse_test, coarse_Tslabels) = keras.datasets.cifar100.load_data(label_mode = 'coarse')
print("Shape of image: {}".format(coarse_train.shape))
print('Coarse Class: {}'.format(np.unique(coarse_Trlabels)))

# STEP 2: Load the data into 'fine labels'
(fine_train, fine_Trlabels), (fine_test, fine_TsLabels) = keras.datasets.cifar100.load_data(label_mode='fine')
print('Fine Class for all: {}'.format(np.unique(fine_Trlabels)))


# 3.) Extract all images of a specific coarse class from the TRAINING DATASET
# The "4" below is the assigned coarse class to "fruits and vegetables" images.
idx = [] # index holder
for i in range(len(coarse_train)):
  if coarse_Trlabels[i][0] == 8: # checks the coarse label of each sample in the training dataset
    idx.append(i) # append the index of an input image with "fruits and vegetables" coarse label.
print('Total images with 8 coarse label (large carnivores) from TRAINING DATASET: {}'.format(len(idx)))
idx = np.array(idx)

# 4.) Extract all image and corresponding "fine" label and store in train_images, train_labels variable list.

train_images, train_labels = fine_train[idx], fine_Trlabels[idx]
print("Shape of the image training dataset:{}".format(train_images.shape))
uniq_fineClass = np.unique(train_labels)
print('Fine Class for the extracted training images:{}'.format(uniq_fineClass))
# 5.) Extract all images of a specific coarse class from the TESTING DATASET
# The "4" below is the assigned coarse class to "fruits and vegetables" images.
idx = []
for i in range(len(coarse_test)):
  if coarse_Tslabels[i][0] == 8: # checks the coarse label of each sample in the testing dataset
    idx.append(i) # append the index of an input image with "fruits and vegetables" coarse label.
print('Total images with 8 coarse label (large carnivores) from TESTING DATASET: {}'.format(len(idx)))
idx = np.array(idx)

# 6.) Extract all image and corresponding "fine" label and store intest_images, test_labels variable list.
test_images, test_labels = fine_test[idx], fine_TsLabels[idx]
print("Shape of the image testing dataset: {}".format(test_images.shape))
uniq_fineClass = np.unique(test_labels)
print('Fine Class for the extracted testing images: {}'.format(uniq_fineClass))

# 7.) Relabel training and testing dataset to start from zero (0).
for i in range(len(uniq_fineClass)):
  for j in range(len(train_labels)):
    if train_labels[j] == uniq_fineClass[i]:
      train_labels[j] = i
  for j in range(len(test_labels)):
    if test_labels[j] == uniq_fineClass[i]:
      test_labels[j] = i

# Plot few samples from images from the TESTING DATASET
plt.figure(figsize=(10,2))
for i in range(5):
  plt.subplot(1,5,i+1)
  plt.xticks([])
  plt.yticks([])
  plt.grid(False)
  plt.imshow(test_images[i], cmap=plt.cm.binary)
  plt.xlabel(test_labels[i])

#Normalizing image data
train_images = train_images / 255.0
test_images = test_images / 255.0

# Data Augmentation
datagen = ImageDataGenerator(
    rotation_range=15,
    width_shift_range=0.1,
    height_shift_range=0.1,
    horizontal_flip=True
)
datagen.fit(train_images)

# Build the model
model = tf.keras.Sequential()

model.add(Conv2D(32, (3,3), activation='relu', padding='same', input_shape=(32,32,3)))
model.add(BatchNormalization())
model.add(MaxPooling2D(2,2))
model.add(Dropout(0.25))

model.add(Conv2D(64, (3,3), activation='relu', padding='same'))
model.add(BatchNormalization())
model.add(MaxPooling2D(2,2))
model.add(Dropout(0.25))

model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.4))

model.add(Dense(len(uniq_fineClass), activation='softmax'))
model.summary()
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.0005),
    loss='sparse_categorical_crossentropy',
    metrics=[tf.keras.metrics.SparseCategoricalAccuracy()]
)

early_stop = tf.keras.callbacks.EarlyStopping(
    monitor='val_loss', patience=7, restore_best_weights=True
)
metricInfo = model.fit(
    datagen.flow(train_images, train_labels, batch_size=32),
    epochs=50,
    validation_data=(test_images, test_labels),
    callbacks=[early_stop]
)
loss = metricInfo.history['loss']
val_loss = metricInfo.history['val_loss']
epochs = range(1, len(loss) + 1)
plt.clf()
plt.plot(epochs, loss, 'g-', label="Training loss")
plt.plot(epochs, val_loss, 'b-', label='Validation loss')
plt.title('Training vs Validation loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()
plt.show()

test_loss, test_acc = model.evaluate(test_images, test_labels)
print(f"Test accuracy: {test_acc:.4f}")

# Test the model on multiple images
str_class = ['bear', 'leopard', 'lion', 'tiger', 'wolf']
predictions = model.predict(test_images, batch_size=32, verbose=1)
predicted_classes = np.argmax(predictions, axis=1)
test_acc = np.mean(predicted_classes == test_labels.flatten())
print(f"Test accuracy from predictions: {test_acc:.4f}")

# Display a grid of test images with predictions
num_images = 15  # change this to show more or fewer images
cols = 5
rows = (num_images + cols - 1) // cols

plt.figure(figsize=(15, rows * 3))
for i in range(num_images):
    plt.subplot(rows, cols, i + 1)
    plt.xticks([])
    plt.yticks([])
    plt.grid(False)
    plt.imshow(test_images[i])

    true_label = int(test_labels[i][0])
    pred_label = predicted_classes[i]
    confidence = predictions[i][pred_label] * 100

    # Green title = correct, Red = wrong
    color = 'green' if pred_label == true_label else 'red'
    plt.title(
        f"Pred: {str_class[pred_label]}\nTrue: {str_class[true_label]}\n{confidence:.1f}%",
        color=color, fontsize=8
    )

plt.suptitle('Large Carnivore Classifier Results', fontsize=14, y=1.02)
plt.tight_layout()
plt.show()