/* Main.c file generated by New Project wizard
 *
 * Created:   Tue Mar 10 2026
 * Processor: PIC16F877A
 * Compiler:  MPLAB XC8
 */

#include <xc.h>

// Add configuration bits
#pragma config FOSC = XT
#pragma config WDTE = OFF
#pragma config PWRTE = ON
#pragma config BOREN = ON
#pragma config LVP = OFF
#pragma config CPD = OFF
#pragma config WRT = OFF
#pragma config CP = OFF

//INTERRUPT SERVICING 
void interrupt ISR() {
    GIE = 0;
    if (INTF) {
        INTF = 0;
        while(RB0){}        // wait for DA to stabilize (active low at RB0)
        unsigned char DATA = PORTD & 0x0F;
        switch (DATA) {
            case 0x00: PORTC = 0x01; break; // 1
            case 0x01: PORTC = 0x02; break; // 2
            case 0x02: PORTC = 0x03; break; // 3
            case 0x04: PORTC = 0x04; break; // 4
            case 0x05: PORTC = 0x05; break; // 5
            case 0x06: PORTC = 0x06; break; // 6
            case 0x08: PORTC = 0x07; break; // 7
            case 0x09: PORTC = 0x08; break; // 8
            case 0x0A: PORTC = 0x09; break; // 9
            case 0x0D: PORTC = 0x00; break; // 0
            default:   PORTC = 0x0F; break;
        }
        while(!RB0){}       // wait for key release
    }
    GIE = 1;
}

//MAIN SUBROUTINE
void main(void)
 {
   TRISB = 0xFF;
   TRISC = 0x00;
   TRISD = 0xFF;
    
   PORTC = 0x00;
   
   //CONFIGURING RB0
   INTEDG = 1;
   INTF = 0;
   INTE = 1;
    
    
   //ENABLE ALL INTERRUPTS
   GIE = 1;

    while(1)
    {
     //7-Segment Display reading carried out by ISR
    }
   
 }